name: Rust Code Compile Check

on:
  pull_request:

jobs:
  compile-check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check compilation
      working-directory: ./src-tauri
      run: cargo check
    
    - name: Run tests
      working-directory: ./src-tauri
      run: cargo test